# Generated by Django 2.0.1 on 2018-03-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classquizresults',
            name='teacher',
        ),
    ]
