# Generated by Django 2.0.1 on 2018-03-11 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_classquizresults_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classquizresults',
            name='teacher',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='polls.Teacher'),
        ),
    ]
