# Generated by Django 2.0.1 on 2018-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_quiz_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(default='Classroom Unit', max_length=200)),
                ('classroom_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='correctAnswer',
            field=models.IntegerField(default=-1),
        ),
    ]
