# Generated by Django 2.0.1 on 2018-03-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_classquizresults_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classquizresults',
            name='course',
        ),
        migrations.RemoveField(
            model_name='classquizresults',
            name='teacher',
        ),
    ]
