# Generated by Django 2.0.1 on 2018-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180305_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correctAnswer',
            new_name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='selected_answer',
            field=models.IntegerField(default=-2),
        ),
        migrations.AddField(
            model_name='quiz',
            name='number_correct',
            field=models.IntegerField(default=0),
        ),
    ]
