# Generated by Django 2.0.1 on 2018-03-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_answerset_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='quiz',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='polls.Quiz'),
        ),
        migrations.AddField(
            model_name='answerset',
            name='student',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='polls.Student'),
        ),
    ]
