# Generated by Django 2.0.1 on 2018-03-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_classquizresults_answerset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
