# Generated by Django 2.0.1 on 2018-03-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180305_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerset',
            name='selections',
        ),
        migrations.AddField(
            model_name='choice',
            name='answer_set',
            field=models.ManyToManyField(to='polls.AnswerSet'),
        ),
    ]
