# Generated by Django 2.0.1 on 2018-03-02 23:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_auto_20180302_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='StudentUser',
        ),
    ]
