# Generated by Django 2.0.1 on 2018-03-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180310_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='classquizresults',
            name='high_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='classquizresults',
            name='low_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
