# Generated by Django 2.0.1 on 2018-03-05 22:57

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('polls', '0007_auto_20180302_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='bio',
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
    ]
