# Generated by Django 2.0.1 on 2018-03-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180306_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerset',
            old_name='choices',
            new_name='answers',
        ),
    ]
