# Generated by Django 2.0.1 on 2018-03-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180306_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
