# Generated by Django 2.0.1 on 2018-03-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_answerset_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title_text',
            field=models.CharField(max_length=200),
        ),
    ]
