# Generated by Django 2.0.1 on 2018-03-10 20:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180310_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 10, 20, 39, 18, 344715, tzinfo=utc), verbose_name='date published'),
        ),
    ]
