# Generated by Django 2.0.1 on 2018-03-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180310_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Better Quiz', 'verbose_name_plural': 'Better Quizzes'},
        ),
    ]
